let challenges = `
At least 5km,
At least 10km,
At least 16km,
At least 21.1km,
At least 30min,
At least 60min,
At least 90min,
At least 120min,
At least #counting,
Clockwise loop,
Counterclockwise loop,
Out-and-back,
Point-to-point,
Strava/GPS art 🎨,
Intervals workout,
Tempo workout,
Progression workout,
Run a race 🏁,
Double run day 🏃‍♂️🏃🏾‍♀️,
Hill Repeats,
Set a Personal Best Effort 🏆,
Strava Segment Top 3 Personal Effort 🏅,
Strava Segment Top 10 🔟,
Take a Segment Crown 🥇,
50m elevation gain ⛰️,
100m elevation gain ⛰️,
200m elevation gain 🗻,
In temperatures greater than 20C 🥵,
In temperatures greater than 30C 🥵,
In temperatures less than 0C 🥶,
In temperatures less than -10C 🥶,
During a precipitation☃,
Run on snow☃ ❄️,
Sunrise run☃ 🌄,
Sunset run☃ 🌇,
Night run: start between 9p-6a local time☃ 🌌,
3rd consecutive day,
7th consecutive day,
12th consecutive day,
Run through a park☃ 🛝,
Trail run☃ 🏞️,
Shore run☃ 🏖️,
Treadmill run,
Track run 🔄,
Cross a bridge 🌉,
Cross a body of water 🌊,
A single loop at least 10 times 🔄,
Run with someone☃ 👫,
Costume Dash☃ 🎅🦌,
Act of Kindness☃ 🎁,
Activity Selfie!!☃ 🤳,
Cross-training activity,
Plogging☃ 🚮,
Run Commute 🏃‍♂️👜,
Holiday Decorations Photograph☃ 📷
`;
