let challenges = `
At least 5km,
At least 10km,
At least 16km,
At least 21.1km,
At least 30min,
At least 60min,
At least 90min,
Clockwise loop,
Counterclockwise loop,
Out-and-back,
Point-to-point,
Intervals workout,
Tempo workout,
Progression workout,
Run a race 🏁,
Set a best estimated effort (Achivement) ⭐,
Make a Strava top 10 segment 🏅,
Take a Segment Crown 🥇,
50m elevation gain ⛰️,
100m elevation gain ⛰️,
200m elevation gain 🗻,
In temperatures greater than 20C 🥵,
In temperatures greater than 30C 🥵,
In temperatures less than 0C 🥶,
In temperatures less than -10C 🥶,
During a precipitation,
Run on snow ❄️,
Sunrise run 🌄,
Sunset run 🌇,
Night run: start between 9p-6a local time 🌌,
3rd consecutive day,
7th consecutive day,
12th consecutive day,
Run through a park 🛝,
Trail run 🏞️,
Treadmill run,
Track run,
Cross a bridge 🌉,
Cross a body of water 🌊,
Run with someone 👫,
Activity Selfie!! 🤳,
Cross-training activity,
Cross-training activity,
Cross-training activity,
Strava art 🎨
`;